### ISSUE TITLE
dosbox-staging snap breaks home directory

### ISSUE THREAD

**Issue by yendor26** [popey/dosbox-staging-snap#12] opened 2022-02-19 21:08 UTC
Hi, when opening dosbox-staging snap version for the first time, all folders in the Home directory of GNU/Linux (Downloads, Documents, etc) become inaccessible, and their icon no longer is a folder, they look instead like some kind of links. Type of file unkown. When trying to open them an error pops up that it cant be opened. (sorry i didnt take screenshots). Even after restarting, removing dosbox-staging and even snapd, the problem remains.

Tested in 3 different distributions: Kubuntu 21.10, Debian 11 and Opensuse Tumbleweed. All with KDE, all same result

Steps to reproduce:

1. Install snapd in a GNU/Linux distribution (tested only in KDE)
1. install dosbox-staging snap
1. Open dosbox-staging, and close
1. Open file manager and see Home directory

**Comment by Recydywa** [comment] 2024-03-25 14:50
As a workaround you can prevent turning those folders into symbolic links by putting at least one file in them. It can be any kind of file. For example empty text file.

Also it seems it affects the directories that are listed in ~/.config/user-dirs.dirs

https://askubuntu.com/questions/1482903/home-directories-turned-into-symbolic-links-without-telling-me-the-reason

More upstream bug reports:

https://github.com/ubuntu/gnome-sdk/issues/188

https://bugs.launchpad.net/ubuntu/+source/okular/+bug/2036597

**Comment by popey** [comment] 2024-03-27 14:33
Thanks again for the issue report @yendor26 and also thanks @Recydywa for the nudge.

I'm gonna close this here because it's not technically a dosbox-staging issue, but one in the gnome-42-2404 content snap. That's now confirmed fixed in the candidate channel, and I'm hopeful with a bit of a push that can be released (once more testing is done) to the stable channel. 

https://github.com/ubuntu/gnome-sdk/issues/188#issuecomment-2022910790

**Closed as completed by popey** 2024-03-27 14:33 UTC
